version: "3.7"
services:
  reactapp:
    image: node
    volumes:
      - "./react-app:/mnt/react-app"
    working_dir: "/mnt/react-app"
    environment:
      PORT: '13000'
      HTTPS: 'true'
    ports:
      - 13000:13000
    entrypoint: "/bin/bash -c"
    command:
      - |
        npm start

  story-api:
    build:
      context: ./story-api
      dockerfile: Dockerfile
    working_dir: /mnt/story-api
    volumes:
      - "./story-api:/mnt/story-api"
    ports:
      - "18080:8080"
    entrypoint: "/bin/bash -c"
    command:
      - |
        pwd
        ls -las
        ./gradlew bootRun --stacktrace

  keycloak:
    image: quay.io/keycloak/keycloak:20.0.3
    environment:
      # KEYCLOAK_USER: admin
      # KEYCLOAK_PASSWORD: admin
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - "./keycloak:/opt/keycloak/data/import"
    ports:
      - "28080:8080"
      - "28443:8443"
    command: start-dev --import-realm