#!/bin/bash

set -o nounset -o errexit

docker run --rm \
  -v "$(pwd):/app" \
  --workdir /app \
  node:latest \
  bash -c "npm ci && npm run build"

echo "💚 Build succesful on $(hostname):$(pwd)"

tree -L 3 ./build/