#!/bin/bash

set -o nounset -o errexit

echo "this is a script to Deploy"

env
pwd

echo "🚩 Getting ready"

# Set the source directory
SOURCE_DIR="./build"

# Use rsync to deploy files
CMD=rsync -avz --delete -e "ssh -p ${SSH_PORT}" \
"${SOURCE_DIR}" ${REMOTE_DIR}
echo "🚨 Jenkins now will execute: $CMD"
$CMD

